// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeOh_NFyyX3CogqtYtUnDcVA9wtowDSDg',
    appId: '1:624206872516:web:f76a8de477c1a7e9672e91',
    messagingSenderId: '624206872516',
    projectId: 'netflix-clone-app-f46eb',
    authDomain: 'netflix-clone-app-f46eb.firebaseapp.com',
    storageBucket: 'netflix-clone-app-f46eb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgUBhAjNjnHcTmPn3w9FubYk2LaAEU4C0',
    appId: '1:624206872516:android:3ed925f2c8c2ee0f672e91',
    messagingSenderId: '624206872516',
    projectId: 'netflix-clone-app-f46eb',
    storageBucket: 'netflix-clone-app-f46eb.appspot.com',
  );
}
